// ── ENTERPRISE VALUE & EQUITY VALUE ───────────────────────────────────────────
const EV = [
{id:"ev.def.meaning", area:"ev", ch:"EV & Equity Value – Concepts", in400:true, d:2, tags:["DEFINITIONAL","EV_VS_EQV"],
 q:"What do equity value and enterprise value mean? Do not explain how you calculate them.",
 ans:"Equity value is the value of everything the company owns, less everything it owes, attributable to common shareholders alone. Enterprise value is the value of the company's core operating business only, regardless of who funds it — it strips out capital structure and non-operating assets, so it is the figure that stays constant when the company changes how it is financed.",
 rub:["Equity value = value to common shareholders","Enterprise value = value of the CORE OPERATING business","Names capital-structure neutrality as the point of EV","Does not recite the bridge formula — the question asked for meaning"],
 def:{term:"Enterprise value"},
 obj:"Equity value answers 'what are the shares worth'; enterprise value answers 'what is the business worth'. Every transaction question reduces to which of those two the transaction touched."},

{id:"ev.bridge", area:"ev", ch:"EV & Equity Value – Concepts", in400:true, d:2, tags:["DEFINITIONAL","EV_VS_EQV"],
 q:"Walk me from diluted equity value to enterprise value.",
 ans:"Start with diluted equity value. Add debt, add preferred stock, add noncontrolling interests, and subtract cash and non-operating assets such as equity investments. You add items that represent other investor groups with a claim on the operating business, and you subtract items that are not part of the operating business. Noncontrolling interests are added because the consolidated financials include 100% of a subsidiary's EBITDA while equity value only captures the parent's share — adding NCI makes the numerator and denominator consistent. Equity investments are subtracted for the mirror reason: their income is not in EBITDA, so their value should not be in enterprise value.",
 rub:["Starts from DILUTED equity value","Adds debt, preferred, NCI","Subtracts cash and non-operating assets / equity investments","Justifies NCI and equity investments by NUMERATOR–DENOMINATOR CONSISTENCY, not by memorized sign"],
 obj:"Every item in the bridge is there to make the numerator match the denominator. If a claim's income is in EBITDA, its value belongs in EV.",
 mc:{p:"Why do you ADD noncontrolling interests in the enterprise value bridge?",
   o:["Consolidated EBITDA already includes 100% of the sub, so EV must reflect the whole sub",
      "Because NCI is a liability",
      "Because the parent owes that money to the minority holders",
      "You subtract NCI, not add it"],c:0,
   t:[null,"BS_SIDE","DEFINITIONAL","DIRECTION"],
   why:["Correct. Consistency between numerator and denominator is the whole reason.",
        "NCI sits in the equity section, not liabilities, and its classification is not the reason it is added.",
        "It is not a debt obligation. It is another group's ownership claim on the consolidated operating business.",
        "Direction inverted. Equity investments are subtracted; NCI is added."]}},

{id:"ev.tsm", area:"ev", ch:"EV & Equity Value – Calculations", in400:true, d:3, tags:["DEFINITIONAL"],
 q:"A company has 200 shares outstanding at $10.00 and 50 options struck at $8.00. What is its diluted equity value?",
 ans:"Under the treasury stock method, the 50 options are in the money so they are exercised, raising 50 × $8.00 = $400 of proceeds. The company uses that $400 to repurchase shares at the $10.00 market price, buying back 40 shares. Net new shares are 50 − 40 = 10, so the diluted share count is 210 and diluted equity value is 210 × $10.00 = $2,100.",
 rub:["Only in-the-money options count","Proceeds = options × strike","Repurchase at the MARKET price, not the strike","Net dilution 10 shares","Diluted equity value $2,100"],
 calc:{p:"200 shares at $10.00, 50 options at an $8.00 strike. Diluted equity value?",ans:2100,tol:1,unit:"$",
   work:"Proceeds 50 × $8 = $400. Repurchase $400 / $10 = 40 shares. Net new = 10. Count = 210. 210 × $10 = $2,100."}},

// ---- #9 transaction effects: funding source vs cash movement ------------------
{id:"ev.txn.issue-stock", area:"ev", ch:"EV & Equity Value – Calculations", in400:true, d:3, tags:["EV_VS_EQV","DIRECTION"],
 q:"A company issues $200 of common stock and holds the proceeds in cash. What happens to equity value and enterprise value?",
 ans:"Equity value rises by $200 — the company issued new shares, so the claim of common shareholders on the business grew by the amount raised. Enterprise value is unchanged: cash rose $200, which reduces net debt by $200, exactly offsetting the $200 increase in equity value. The core operating business did not change, which is what enterprise value measures.",
 rub:["Equity value UP $200","Enterprise value UNCHANGED","Explains the offset through the bridge","Names the principle: funding source drives equity value; cash movement drives EV"],
 obj:"Funding source determines equity value. Cash movement determines enterprise value. Run both tests separately and you never invert this family of questions.",
 binary:{p:"Issues $200 of stock, holds it in cash. Enterprise value:",a:"Up $200",b:"Unchanged",c:1,why:"EqV +200 and cash +200 cancel in the bridge. EV measures the operating business, which did not change."}},

{id:"ev.txn.issue-debt-factory", area:"ev", ch:"EV & Equity Value – Calculations", in400:true, d:3, tags:["EV_VS_EQV"],
 q:"A company issues $100 of debt to buy a factory. What happens to equity value and enterprise value?",
 ans:"Equity value is unchanged — the funding came from debt, not from shareholders, and the company received an asset worth what it paid. Enterprise value rises by $100: debt rose $100 while cash is unchanged, so net debt rose $100, and the company now owns an additional $100 of operating assets. The operating business genuinely got bigger.",
 rub:["Equity value UNCHANGED — debt-funded","Enterprise value UP $100","Cash did not move; debt did","Connects the EV increase to the larger operating asset base"],
 binary:{p:"Issues $100 of debt to buy a factory. Equity value:",a:"Unchanged",b:"Up $100",c:0,why:"Debt-funded, and the cash immediately bought an asset of equal value. Shareholders' claim is unchanged."}},

{id:"ev.txn.cash-acquire", area:"ev", ch:"EV & Equity Value – Calculations", in400:true, d:4, tags:["EV_VS_EQV","DIRECTION"],
 q:"A company uses $100 of its existing cash to acquire another business worth $100. What happens to equity value and enterprise value?",
 ans:"Equity value is unchanged — the company swapped $100 of cash for $100 of operating assets, and no new shares were issued. Enterprise value rises by $100: cash fell $100, so net debt rose $100 while equity value stayed flat. Economically that is right, because the company converted a non-operating asset into operating assets, and enterprise value counts only the operating side.",
 rub:["Equity value UNCHANGED","Enterprise value UP $100","Explains the conversion of non-operating cash into operating assets","Does not claim both move"],
 obj:"Cash is a non-operating asset. Spending it on an operating business raises enterprise value even though nothing about shareholder wealth changed.",
 mc:{p:"A company acquires a $100 business using $100 of existing cash. Equity value and enterprise value?",
   o:["EqV unchanged, EV +$100","EqV −$100, EV unchanged","EqV unchanged, EV unchanged","EqV +$100, EV +$100"],c:0,
   t:[null,"EV_VS_EQV","EV_VS_EQV","DIRECTION"],
   why:["Correct. No shares issued, so equity value is flat; cash became operating assets, so EV rises.",
        "Equity value does not fall — the company received $100 of assets for its $100 of cash. This is the buyback answer applied to the wrong question.",
        "EV must rise: a non-operating asset became an operating one.",
        "No new shares were issued, so equity value cannot rise."]}},

{id:"ev.txn.find-cash", area:"ev", ch:"EV & Equity Value – Calculations", in400:false, d:3, tags:["EV_VS_EQV","DIRECTION"],
 q:"A company finds $100 on the ground. What happens to enterprise value?",
 ans:"Enterprise value is unchanged. Equity value rises by $100 because shareholders are $100 richer, but cash also rose by $100, and the two offset in the bridge. The operating business is exactly as productive as it was a minute earlier, and that is what enterprise value measures.",
 rub:["Enterprise value UNCHANGED","Equity value UP $100","Names the offset","States the intuition: the operating business did not change"],
 binary:{p:"A company finds $100 on the ground. Enterprise value:",a:"Up $100",b:"Unchanged",c:1,why:"Windfall cash raises equity value and cash equally. They cancel. EV only moves when the operating business changes."}},

{id:"ev.txn.preferred-dividend", area:"ev", ch:"EV & Equity Value – Calculations", in400:true, d:3, tags:["EV_VS_EQV","BS_SIDE"],
 q:"A company pays $10 of common dividends and $10 of preferred dividends. What happens to equity value and enterprise value?",
 ans:"Equity value falls by $10 — only the common dividend reduces the common shareholders' claim; the preferred dividend is a payment to a different investor group that was never inside equity value. Enterprise value is unchanged by the common dividend, since cash fell $10 and equity value fell $10 and they offset. The preferred dividend reduces cash by $10 without reducing equity value, so it raises enterprise value by $10 — although in practice the preferred balance is also reduced if it was accrued. Handle the two payments separately.",
 rub:["Common dividend: EqV −10, EV unchanged","Preferred dividend does NOT reduce common equity value","Treats the two payments separately rather than lumping them","Keeps the bridge consistent"]},

{id:"ev.negative", area:"ev", ch:"EV & Equity Value – Concepts", in400:true, d:3, tags:["DIRECTION"],
 q:"Could equity value ever be negative? Could enterprise value?",
 ans:"Market equity value cannot be negative, because a share price cannot go below zero — shareholders have limited liability. Book equity can easily be negative, for instance after large buybacks or accumulated losses. Enterprise value can be negative, when a company holds more cash than its equity value plus debt — this happened to a number of cash-rich, deeply out-of-favour companies, and it implies the market is assigning the operating business a negative value.",
 rub:["Distinguishes MARKET equity value (cannot be negative) from BOOK equity (can be)","Enterprise value CAN be negative","Names the condition: cash exceeds equity value plus debt","Does not conflate the two"],
 binary:{p:"Market equity value can be negative.",a:"True",b:"False",c:1,why:"Limited liability floors a share price at zero. Book equity is a different thing and can be deeply negative."}},

{id:"ev.nci-consolidation", area:"ev", ch:"EV & Equity Value – Calculations", in400:false, d:5, tags:["EV_VS_EQV","DEFINITIONAL"],
 q:"A parent owns 100% of a private coffee business with $100M EBITDA and 80% of a public donut business with $200M EBITDA that trades at 5x EBITDA. The parent has 100M shares at $10, $500M of debt and $200M of cash. Find the parent's consolidated EV/EBITDA and the implied multiple on the coffee business.",
 ans:"Parent equity value is 100M × $10 = $1,000M. Consolidated enterprise value is $1,000M + $500M debt − $200M cash + noncontrolling interest. The donut business is worth 5 × $200M = $1,000M of enterprise value, and the 20% the parent does not own is $200M, which is the NCI. So consolidated EV is $1,000 + $500 − $200 + $200 = $1,500M. Consolidated EBITDA is $100M + $200M = $300M because consolidation includes 100% of the donut EBITDA. Consolidated EV/EBITDA is $1,500 / $300 = 5.0x. To isolate the coffee business, strip out the donut business's full $1,000M enterprise value: $1,500 − $1,000 = $500M against $100M of EBITDA, so the coffee business is implied at 5.0x.",
 rub:["Adds NCI at the minority share of the SUB's enterprise value","Uses 100% of the sub's EBITDA in the denominator","Consolidated 5.0x","Strips the sub's FULL EV, not the parent's 80% share","Coffee implied at 5.0x"],
 calc:{p:"Parent: 100M shares at $10, $500M debt, $200M cash, owns 80% of a sub worth 5x on $200M EBITDA, plus a wholly-owned unit with $100M EBITDA. Implied EV/EBITDA of the wholly-owned unit?",ans:5,tol:0.1,unit:"x",
   work:"EqV 1,000 + debt 500 − cash 200 + NCI 200 = EV 1,500. Strip the sub's full EV of 1,000 → 500. 500 / 100 EBITDA = 5.0x."}},

{id:"ev.multiple-choice-numerator", area:"ev", ch:"Valuation Metrics and Multiples", in400:true, d:2, tags:["EV_VS_EQV","DEFINITIONAL"],
 q:"How do you decide whether a multiple uses equity value or enterprise value in the numerator?",
 ans:"Match the numerator to whom the denominator's cash flow belongs. If the metric is available to all investors — revenue, EBITDA, EBIT, unlevered free cash flow, all of which sit above the interest line — pair it with enterprise value. If the metric is available only to common shareholders — net income, earnings per share, levered free cash flow, all after interest — pair it with equity value. The error to avoid is a mismatched pair like EV/net income or equity value over EBITDA, because the numerator would include claims the denominator has already paid off, or vice versa.",
 rub:["States the consistency rule as the principle","Above the interest line → EV","After interest → equity value","Names a concrete invalid pair"],
 obj:"One test settles every multiple question: whose money is in the denominator?",
 mc:{p:"Of EV/EBITDA, P/E and equity value / EBIT, which one is invalid?",
   o:["Equity value / EBIT","EV/EBITDA","P/E","All three are valid"],c:0,
   t:[null,"EV_VS_EQV","EV_VS_EQV","EV_VS_EQV"],
   why:["Correct. EBIT is pre-interest, so it belongs to all investors, but equity value is a common-shareholders-only figure. Mismatched.",
        "Valid — both are all-investor figures.",
        "Valid — both are common-shareholder figures.",
        "Equity value / EBIT is the classic mismatch; this exact question shows up in Evercore first rounds."]},
 binary:{p:"EV / net income is a valid multiple.",a:"True",b:"False",c:1,why:"Net income is after interest, so it belongs to common shareholders only. Pairing it with an all-investor numerator double-counts the lenders."}}
];
