// ── VALUATION ─────────────────────────────────────────────────────────────────
const VAL = [
{id:"val.dcf.walkthrough", area:"valuation", ch:"DCF – Assumptions and Analysis", in400:true, d:3, tags:["DEFINITIONAL","WRONG_STATEMENT"],
 q:"Walk me through a DCF.",
 ans:"You project the company's unlevered free cash flow over an explicit forecast period, usually five to ten years. Unlevered free cash flow is EBIT, times one minus the tax rate, plus depreciation and amortization and other non-cash charges, minus the increase in working capital, minus capital expenditures. You discount those cash flows at WACC, because unlevered cash flow is available to all investors. You then calculate a terminal value, either by growing the final year's cash flow at a perpetual growth rate and dividing by WACC minus that growth rate, or by applying an exit multiple to the final year's EBITDA, and you discount the terminal value back at the same WACC. Summing the discounted cash flows and the discounted terminal value gives implied enterprise value. Finally you bridge to implied equity value by subtracting debt and preferred and noncontrolling interests and adding cash, and divide by the diluted share count to get implied value per share.",
 rub:["Projects UNLEVERED free cash flow","Names the UFCF build: EBIT(1−t) + D&A − ΔWC − CapEx","Discounts at WACC and says why (all investors)","Both terminal value methods named","Discounts the terminal value back too","Result is ENTERPRISE value, then bridges to equity","Divides by DILUTED shares"],
 obj:"A DCF produces enterprise value first. Every candidate who says 'and that gives you the share price' has skipped the bridge.",
 target:90},

{id:"val.dcf.ufcf-build", area:"valuation", ch:"DCF – Assumptions and Analysis", in400:true, d:3, tags:["DEFINITIONAL","LEVEL_NOT_DELTA"],
 q:"How do you get from revenue to unlevered free cash flow?",
 ans:"Revenue less cost of goods sold and operating expenses gives EBIT. Multiply EBIT by one minus the tax rate to get net operating profit after tax. Add back depreciation, amortization and other non-cash charges. Subtract the increase in working capital. Subtract capital expenditures. Interest is never subtracted, because unlevered free cash flow is the cash available to all investors before any capital structure decision.",
 rub:["EBIT × (1 − t)","Adds back D&A","Subtracts the INCREASE in working capital — a delta","Subtracts CapEx","Explicitly excludes interest and says why"],
 binary:{p:"Unlevered free cash flow subtracts interest expense.",a:"True",b:"False",c:1,why:"Unlevered means before financing. Subtracting interest would make it levered and it would then have to be discounted at cost of equity, not WACC."},
 def:{term:"Unlevered free cash flow"}},

{id:"val.wacc", area:"valuation", ch:"DCF – The Discount Rate", in400:true, d:3, tags:["DEFINITIONAL"],
 q:"What is WACC and how do you calculate it?",
 ans:"WACC is the blended annual return a company must earn to satisfy all of its investors. It is the cost of equity times the proportion of equity in the capital structure, plus the cost of debt times one minus the tax rate times the proportion of debt, plus the cost of preferred times the proportion of preferred. The after-tax adjustment applies only to debt because interest is tax deductible. It pairs with unlevered free cash flow because both are all-investor figures.",
 rub:["Blended required return across all capital providers","Weights are at MARKET value, not book","Only the debt cost is tax-affected","Pairs with unlevered FCF"],
 def:{term:"WACC"},
 binary:{p:"The weights in WACC are based on book values of debt and equity.",a:"True",b:"False",c:1,why:"Market values. Book equity in particular bears almost no relationship to what shareholders actually require."}},

{id:"val.capm", area:"valuation", ch:"DCF – The Discount Rate", in400:true, d:2, tags:["DEFINITIONAL"],
 q:"How do you calculate the cost of equity?",
 ans:"Under CAPM, cost of equity equals the risk-free rate plus levered beta times the equity risk premium, and you may add a size premium or country risk premium. The risk-free rate is the yield on a government bond matched to the cash flow horizon, typically the ten- or twenty-year treasury. The equity risk premium is the excess return equities have historically delivered over that risk-free rate. Beta measures how volatile the stock is relative to the market as a whole.",
 rub:["Rf + β × ERP (+ premia)","Risk-free = long-dated government bond matched to horizon","ERP = equity excess return over risk-free","Beta = sensitivity to the market"],
 def:{term:"Cost of equity"}},

{id:"val.beta", area:"valuation", ch:"DCF – The Discount Rate", in400:true, d:4, tags:["DEFINITIONAL","DIRECTION"],
 q:"What is beta, and why do you unlever and relever it?",
 ans:"Beta measures a stock's volatility relative to the overall market — a beta of 1.5 means the stock has historically moved one and a half times as much as the market. The betas you observe for comparable companies are levered betas, which reflect both business risk and each company's own capital structure. You unlever each comparable's beta to strip out its leverage, using unlevered beta equals levered beta divided by one plus one minus the tax rate times debt over equity. That isolates pure business risk. You take the median unlevered beta across the comparables and relever it at the target company's own capital structure, using the same formula in reverse. This gives a beta that reflects the industry's business risk at your company's leverage.",
 rub:["Volatility relative to the market","Observed betas are LEVERED","Unlever: βL / (1 + (1−t)(D/E))","Median across comps, then relever at the TARGET's structure","Names the purpose: isolate business risk from financing risk"],
 binary:{p:"Higher leverage, holding business risk constant, makes levered beta…",a:"Higher",b:"Lower",c:0,why:"Debt amplifies equity returns in both directions. More leverage = riskier equity = higher levered beta = higher cost of equity."},
 calc:{p:"Comparable has a levered beta of 1.20, D/E of 50%, tax rate 40%. What is its unlevered beta?",ans:0.923,tol:0.01,unit:"",
   work:"βU = 1.20 / (1 + (1 − 0.40)(0.50)) = 1.20 / 1.30 = 0.923."}},

{id:"val.debt-cheaper", area:"valuation", ch:"DCF – The Discount Rate", in400:true, d:2, tags:["DIRECTION","DEFINITIONAL"],
 q:"Why is equity more expensive than debt?",
 ans:"Debt holders sit senior in the capital structure, so they are paid first in a bankruptcy, they usually hold security over assets, and their return is contractually fixed. Equity holders are residual claimants paid last with no contractual return, so they demand a higher expected return for bearing that risk. On top of that, interest on debt is tax deductible while dividends are not, which lowers the effective after-tax cost of debt further.",
 rub:["Seniority in the capital structure","Contractual vs residual claim","Tax deductibility of interest","Frames it as required RETURN, not as a cash cost"],
 binary:{p:"If debt is cheaper, a company should use as much of it as possible.",a:"True",b:"False",c:1,why:"Beyond a point, more leverage raises both the cost of debt and the cost of equity as financial distress risk rises, so WACC eventually turns up. There is an optimal structure, not a corner solution."}},

{id:"val.tv-gordon", area:"valuation", ch:"DCF – Assumptions and Analysis", in400:true, d:3, tags:["DEFINITIONAL","DIRECTION"],
 q:"What is the intuition behind the Gordon Growth terminal value formula, and why must the growth rate be below WACC?",
 ans:"Terminal value equals the final year's free cash flow grown one year, divided by WACC minus the terminal growth rate. It is the present value at the end of the forecast period of a cash flow stream growing at a constant rate forever. If the growth rate equalled or exceeded WACC the denominator would be zero or negative, producing an infinite or negative value — which is the mathematical expression of the fact that a business cannot grow faster than the required return in perpetuity without eventually becoming larger than the entire economy. The terminal growth rate should therefore be at or below long-run GDP or inflation, typically 2 to 3 percent in developed markets.",
 rub:["Formula: FCF(n) × (1+g) / (WACC − g)","It is the value AT the end of the forecast period — must still be discounted back","g ≥ WACC breaks the formula","Ties the cap to long-run GDP/inflation"],
 obj:"Terminal value is a value at year n, not a present value. Forgetting to discount it back is the single most common DCF mechanical error."},

{id:"val.tv-share", area:"valuation", ch:"DCF – Assumptions and Analysis", in400:true, d:3, tags:["DIRECTION"],
 q:"How do you check whether your terminal value is reasonable?",
 ans:"Cross-check the two methods against each other: back into the implied exit multiple from your Gordon Growth terminal value, and back into the implied perpetual growth rate from your multiples-based terminal value. If the implied growth rate is above long-run GDP or the implied multiple is far outside the comparable company range, your assumptions are inconsistent. Also check what share of total enterprise value the terminal value represents — if it is above roughly 75 to 80 percent, the DCF is really a multiples valuation with extra steps and the explicit forecast is doing almost no work.",
 rub:["Cross-check each method against the other's implied output","Compare the implied multiple to the comp range","Compare the implied growth rate to long-run GDP","Terminal value share of total EV, with a rough threshold"],
 calc:{p:"A DCF has $200 of discounted explicit-period cash flow and $800 of discounted terminal value. What share of enterprise value is the terminal value?",ans:80,tol:0.5,unit:"%",
   work:"800 / (200 + 800) = 80%. Above the ~75% rule of thumb, so the explicit forecast is carrying very little of the valuation."}},

{id:"val.midyear", area:"valuation", ch:"DCF – Assumptions and Analysis", in400:true, d:3, tags:["DIRECTION"],
 q:"Why use the mid-year convention, and which way does it move the valuation?",
 ans:"The standard convention discounts each year's cash flow as though it all arrives on the last day of that year. In reality cash is generated roughly evenly through the year. The mid-year convention discounts each year's cash flow from its midpoint instead, using exponents of 0.5, 1.5, 2.5 and so on. Because cash is being received earlier, it is discounted less, so the mid-year convention raises the implied valuation — usually by a few percent.",
 rub:["Standard assumes year-end receipt","Mid-year uses 0.5, 1.5, 2.5 exponents","Raises valuation — states the DIRECTION explicitly","Explains why: earlier receipt, less discounting"],
 binary:{p:"Switching to the mid-year convention makes the implied valuation…",a:"Higher",b:"Lower",c:0,why:"Cash arrives sooner, so it is discounted less. Higher. This is a direction question — the mechanics are easy and the sign is what gets missed."}},

{id:"val.methodologies", area:"valuation", ch:"Valuation Methodologies", in400:true, d:2, tags:["DEFINITIONAL","DIRECTION"],
 q:"What are the main valuation methodologies, and which produces the highest value?",
 ans:"The three core methods are comparable public companies, precedent transactions, and the discounted cash flow. Precedent transactions usually produce the highest values because acquirers pay a control premium and can justify it with synergies. Comparable companies reflect where minority stakes trade with no control premium, so they are typically lowest of the three. A DCF is usually the highest or close to it because it rests on management-case projections and a terminal value, though its range is the widest because it is the most assumption-sensitive. An LBO analysis is often added as a floor valuation, since it answers the minimum a financial sponsor would need to pay to hit its return target.",
 rub:["Names all three core methods","Precedents highest — and says WHY (control premium, synergies)","Comps lowest — no control premium","DCF widest range, most assumption-sensitive","LBO sets a floor"],
 binary:{p:"Precedent transactions typically produce values that are…",a:"Higher than comps",b:"Lower than comps",c:0,why:"Acquirers pay a control premium over the trading price. That premium is the whole difference."}},

{id:"val.comps-vs-precedents", area:"valuation", ch:"Valuation Methodologies", in400:true, d:3, tags:["DEFINITIONAL"],
 q:"What are the advantages and disadvantages of comparable companies versus precedent transactions?",
 ans:"Comparable companies use current market data, so they are always up to date and the underlying financials are public and reliable. But they reflect minority stakes with no control premium, and no two companies are truly comparable. Precedent transactions capture what acquirers actually paid, including control premiums and synergy expectations, which is the relevant reference point for an M&A process. But the data is often stale — a deal from three years ago reflects a different rate environment and different market conditions — private targets disclose little, and the strategic rationale of any one deal may not repeat.",
 rub:["Comps: current, reliable data; no control premium","Precedents: real prices paid with control premium; stale and thin data","Names the rate/market-environment problem for precedents","Does not just list — pairs each advantage with its matching weakness"]},

{id:"val.margin-backsolve", area:"valuation", ch:"Valuation Metrics and Multiples", in400:false, d:3, tags:["DEFINITIONAL"],
 q:"A company trades at 3.0x EV/revenue and 5.0x EV/EBITDA. What is its EBITDA margin?",
 ans:"Enterprise value is the same number in both multiples, so revenue times 3.0 equals EBITDA times 5.0. EBITDA over revenue is therefore 3.0 divided by 5.0, or 60 percent.",
 rub:["Recognizes EV is common to both","EBITDA margin = EV/rev multiple ÷ EV/EBITDA multiple","60%"],
 calc:{p:"EV/revenue 3.0x and EV/EBITDA 5.0x. EBITDA margin?",ans:60,tol:0.5,unit:"%",
   work:"EV is the same in both. 3.0 × Revenue = 5.0 × EBITDA → EBITDA/Revenue = 3.0/5.0 = 60%."}},

{id:"val.tax-backsolve", area:"valuation", ch:"Valuation Metrics and Multiples", in400:false, d:5, tags:["EV_VS_EQV","DEFINITIONAL"],
 q:"A company has a P/E of 20x, EV/EBITDA of 10x, interest expense of $20M at a 5% rate, D&A of $20M and a market cap of $200M. What is its effective tax rate?",
 ans:"Market cap $200M at a 20x P/E gives net income of $10M. Interest expense of $20M at a 5% rate implies debt of $400M. Enterprise value is $200M of equity plus $400M of debt, or $600M assuming no cash, and at 10x that gives EBITDA of $60M. Subtract $20M of D&A for EBIT of $40M, then subtract $20M of interest for pre-tax income of $20M. Net income is $10M, so taxes are $10M and the effective tax rate is 50 percent.",
 rub:["Net income from market cap ÷ P/E","Debt from interest ÷ rate","EV = equity + debt (states the no-cash assumption)","EBITDA from EV ÷ multiple","Walks EBITDA → EBIT → pre-tax → net income in order","50%"],
 obj:"This chain — P/E and EV/EBITDA together back into the whole income statement — appeared in four of five real Evercore first-round sets. Practise it until it is automatic.",
 calc:{p:"P/E 20x, EV/EBITDA 10x, interest $20M at 5%, D&A $20M, market cap $200M. Effective tax rate?",ans:50,tol:0.5,unit:"%",
   work:"NI = 200/20 = 10. Debt = 20/0.05 = 400. EV = 200 + 400 = 600. EBITDA = 600/10 = 60. EBIT = 60 − 20 = 40. Pre-tax = 40 − 20 = 20. Tax = 20 − 10 = 10. Rate = 10/20 = 50%."},
 target:150}
];
